---
- name: enable epel
  yum: name=epel-release state=latest

- name: upgrade all packages
  yum: name=* state=latest

- name: Install git
  yum: name=git state=present

- name: Install python
  yum: name=python state=present

- name: Install python-devel
  yum: name=python-devel state=present

- name: Install pip
  command: easy_install pip

- name: Install virtualenv
  command: pip install virtualenv

- name: Install gettext
  yum: name=gettext state=present

- name: Install memcached
  yum: name=memcached state=present

- name: Enable memcached
  service: name=memcached enabled=yes state=started

- name: Install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: Create mirrors user
  user: name=mirrors shell=/bin/bash